language: python

python:
    - 2.7

virtualenv:
    system_site_packages: true

compiler:
    - g++

before_install:
    # Add appropriate directories to various paths.
    #- "export PYHOME=$HOME/virtualenv/python${TRAVIS_PYTHON_VERSION}"
    #- export PYTHONPATH=$PYHOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH
    #- export PATH=$HOME/bin:$PYHOME/bin:$PATH
    #- export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
    #- "export PIP_TARGET=$PYHOME/include/python$TRAVIS_PYTHON_VERSION{a:0:3}"

    - "sudo apt-get -qq update"
    # Non-pip dependency
    - "sudo apt-get install -y libffi-dev libssl-dev python-dev"
    - "sudo pip install --user requests[security]"
    # GalSim dependencies
    - "sudo apt-get install -y libfftw3-dev libav-tools libeigen3-dev cmake"
    #- "sudo pip install --user pybind11"
    # Install GalSim
    - "sudo pip install --user galsim"
   
cache:
    ccache: true
    pip: true

install:
    # SLRealizer dependencies
    - "sudo pip install --user -r requirements.txt"

script:
    - "python -c 'import galsim; galsim.__file__'"
    - "python -c 'import numpy; numpy.__file__'"
    - "python setup.py install"
    - "pwd"
    - "source configure.sh"
    - "cd slrealizer/tests"
    - "python test_analytical_moments.py"
    - "python test_om10realizer.py"
    - "python test_sdssrealizer.py"
    - "pwd"

after_success:
    - codecov